In [1]:
import numpy as np

In [28]:
arr = np.array([[1,2,3,4,5],
                [2,3,4,5,6],
                [12,23,34,45,34]])
print(arr.shape)
print(len(arr))
print(arr)


(3, 5)
3
[[ 1  2  3  4  5]
 [ 2  3  4  5  6]
 [12 23 34 45 34]]


In [37]:
a = np.array([1,2,3,4])
b = np.array([4,5,6,7])
c = np.dot(a,b)
np.linalg.norm(a)

np.float64(5.477225575051661)